name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to S3
      run: |
        aws s3 sync out/ s3://intellilearn-final/ --delete --region us-east-1
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E1UF9C891JJD1F --paths "/*" --region us-east-1
        
    - name: Deployment completed
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "🌐 Application available at: https://d2sn3lk5751y3y.cloudfront.net/" 